### ISSUE TITLE
Why default to OpenDNS instead of using system's DNS?

### ISSUE THREAD

**Issue by theel0ja** [silverwind/dnsbl#9]
The line of code in question:
https://github.com/silverwind/dnsbl/blob/66ea1e55f0588bf783b93989af18951bca0fe754/index.js#L10

**Comment by silverwind** [comment]
This is because of Spamhaus who apparently block any DNS server that sends too many requests in a given timeframe, so doing it via system resolvers can be unreliable. Try running these a few times and you will see:

```
dig @8.8.8.8 2.0.0.127.zen.spamhaus.org a
dig @1.1.1.1 2.0.0.127.zen.spamhaus.org a
dig @208.67.220.220 2.0.0.127.zen.spamhaus.org a
```

OpenDNS seems to be in some kind of rate limit exemption or something, it's the only server that gives me consistent Spamhaus results.

**Comment by theel0ja** [comment]
Found this:

https://www.spamhaustech.com/news/successfully-accessing-spamhauss-free-block-lists-using-a-public-dns/
